spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mess?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mess
    password: mess

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true 시스템아웃 로그만 찍히기 때문에 주석.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug